Repository gisaia/ARLAS-server, pull requests merged in 2018-03, with the labels that each got.

#205 generate arlas-api using typescript-fetch
  Dockerfile-swagger-codegen
  conf/npm/package-build.json
  conf/npm/package-publish.json
  conf/npm/tsconfig-build.json
  release.sh
  scripts/build-swagger-codegen.sh
Labels: API

#213 fix : make ATOM integration tests resilients to custom arlas paths
  src/test/java/io/arlas/server/rest/explore/ATOMSearchServiceIT.java
Labels: bug

#222 Remove Include field property in collection
  src/main/java/io/arlas/server/core/ElasticAdmin.java
  src/main/java/io/arlas/server/core/ElasticDocument.java
  src/main/java/io/arlas/server/core/FluidSearch.java
  src/main/java/io/arlas/server/dao/ElasticCollectionReferenceDaoImpl.java
  src/main/java/io/arlas/server/model/CollectionReference.java
  src/main/java/io/arlas/server/model/CollectionReferenceParameters.java
  src/main/java/io/arlas/server/wfs/operation/describefeaturetype/DescribeFeatureTypeHandler.java
  src/main/java/io/arlas/server/wfs/operation/getfeature/GetFeatureHandler.java
  src/main/java/io/arlas/server/wfs/utils/XmlUtils.java
  src/test/java/io/arlas/server/AbstractTestContext.java
  src/test/java/io/arlas/server/CollectionTool.java
  src/test/java/io/arlas/server/Data.java
  src/test/java/io/arlas/server/DataSetTool.java
  src/test/java/io/arlas/server/rest/collections/CollectionServiceIT.java
  src/test/java/io/arlas/server/rest/explore/ATOMSearchServiceIT.java
  src/test/java/io/arlas/server/rest/explore/RawServiceIT.java
  src/test/java/io/arlas/server/rest/explore/SearchServiceIT.java
  src/test/resources/dataset.mapping.json
Labels: bug, feature
