Repository gisaia/ARLAS-server, pull requests merged in 2018-10, with the labels that each got.

#349 Fix typo in doc raster Tile
  docs/arlas-collection-model.md
Labels: documentation

#348 Fix shape orientation Bbox
  arlas-core/src/main/java/io/arlas/server/core/FluidSearch.java
Labels: type:bug

#354 Bump dropwizard dependencies' versions
  arlas-core/pom.xml
  arlas-server/src/main/java/io/arlas/server/app/ArlasServer.java
  pom.xml
Labels: type:maintenance

#358 Fix openseach documentation
  docs/arlas-collection-model.md
Labels: documentation, type:maintenance
