Repository gisaia/ARLAS-server, pull requests merged in 2018-07, with the labels that each got.

#328 Made `scripts/wait-for-elasticsearch.sh` support environment variable…
  docker-compose.yml
  scripts/wait-for-elasticsearch.sh
Labels: container, type:enhancement

#329 Fixed README CI badge.
  README.md
Labels: documentation, type:maintenance

#330 Increase max zoom for tiled geosearch
  arlas-core/src/main/java/io/arlas/server/utils/CheckParams.java
  arlas-tests/src/test/java/io/arlas/server/rest/explore/AbstractXYZTiledTest.java
Labels: type:enhancement
