Repository gisaia/ARLAS-server, pull requests merged in 2019-11, with the labels that each got.

#541 Fix Datehistogram key bug due to bump to ES7
  arlas-core/src/main/java/io/arlas/server/core/FluidSearch.java
  arlas-core/src/main/java/io/arlas/server/services/ExploreServices.java
  arlas-tests/src/test/java/io/arlas/server/rest/explore/AbstractAggregatedTest.java
  arlas-tests/src/test/java/io/arlas/server/rest/explore/AggregateServiceIT.java
  arlas-tests/src/test/java/io/arlas/server/rest/explore/GeoAggregateServiceIT.java
Labels: type:bug

#543 [Server] Generate API documentation
  release.sh
Labels: documentation

#499 Authentication mode support
  .travis.yml
  arlas-admin/pom.xml
  arlas-admin/src/main/java/io/arlas/server/auth/ArlasClaims.java
  arlas-admin/src/main/java/io/arlas/server/auth/AuthenticationFilter.java
  arlas-admin/src/main/java/io/arlas/server/auth/AuthorizationFilter.java
  arlas-admin/src/main/java/io/arlas/server/auth/RuleClaim.java
  arlas-core/src/main/java/io/arlas/server/app/ArlasAuthConfiguration.java
  arlas-core/src/main/java/io/arlas/server/app/ArlasServerConfiguration.java
  arlas-server/src/main/java/io/arlas/server/app/ArlasServer.java
  arlas-tests/src/test/java/io/arlas/server/auth/AuthServiceIT.java
  arlas-tests/src/test/resources/arlas-test.pem
  conf/configuration.yaml
  docker-compose.yml
  docs/arlas-api.md
  pom.xml
  scripts/tests-integration-stage.sh
  scripts/tests-integration.sh
Labels: security

#553 Document env var `ARLAS_APP_PATH`
  docs/arlas-server-configuration.md
Labels: conf, documentation, type:maintenance
