Repository gisaia/ARLAS-server, pull requests merged in 2020-08, with the labels that each got.

#643 No longer escaping replacement value in Auth header variables.
  arlas-admin/src/main/java/io/arlas/server/auth/ArlasClaims.java
  arlas-admin/src/main/java/io/arlas/server/auth/AuthenticationFilter.java
  arlas-admin/src/main/java/io/arlas/server/auth/AuthorizationFilter.java
  arlas-core/src/main/java/io/arlas/server/app/ArlasAuthConfiguration.java
  arlas-core/src/main/java/io/arlas/server/app/ArlasBaseConfiguration.java
  arlas-server/src/main/java/io/arlas/server/app/ArlasServer.java
  conf/configuration.yaml
Labels: type:enhancement

#645 Fix jwtVerifier
  arlas-admin/src/main/java/io/arlas/server/auth/AuthorizationFilter.java
Labels: type:enhancement

#649 Feature/add cors conf
  arlas-admin/src/main/java/io/arlas/server/auth/AuthorizationFilter.java
  arlas-core/src/main/java/io/arlas/server/app/ArlasBaseConfiguration.java
  arlas-core/src/main/java/io/arlas/server/app/ArlasCorsConfiguration.java
  arlas-core/src/main/java/io/arlas/server/app/ArlasServerConfiguration.java
  arlas-server/src/main/java/io/arlas/server/app/ArlasServer.java
  arlas-tests/src/test/java/io/arlas/server/rest/CORSIT.java
  conf/configuration.yaml
  docker-compose.yml
  docs/arlas-server-configuration.md
  scripts/tests-integration-stage.sh
Labels: conf, type:breaking

#650 Fix silent error in _import
  arlas-core/src/main/java/io/arlas/server/impl/elastic/utils/ElasticClient.java
  arlas-rest/src/main/java/io/arlas/server/rest/collections/CollectionService.java
Labels: type:bug
