Repository gisaia/ARLAS-server, pull requests merged in 2020-10, with the labels that each got.

#662 Bump to elasticsearch 7.9.2
  README.md
  arlas-core/src/main/java/io/arlas/server/impl/elastic/dao/ElasticCollectionReferenceDao.java
  arlas-core/src/main/java/io/arlas/server/impl/elastic/utils/ElasticTool.java
  docker-compose-elasticsearch.yml
  pom.xml
  release.sh
  scripts/tests-integration-elasticsearch.sh
  scripts/tests-integration.sh
Labels: dependencies, type:enhancement

#661 Fix template matching for a given collection index pattern
  arlas-core/src/main/java/io/arlas/server/impl/elastic/utils/ElasticClient.java
Labels: type:bug

#658 Allow a difference of 3 between '_geoaggregate/{geohash}' precision …
  arlas-core/src/main/java/io/arlas/server/exceptions/ArlasExceptionMapper.java
  arlas-core/src/main/java/io/arlas/server/exceptions/ConstraintViolationExceptionMapper.java
  arlas-core/src/main/java/io/arlas/server/exceptions/IllegalArgumentExceptionMapper.java
  arlas-core/src/main/java/io/arlas/server/exceptions/JsonProcessingExceptionMapper.java
  arlas-rest/src/main/java/io/arlas/server/rest/explore/aggregate/GeoAggregateRESTService.java
Labels: type:enhancement
